version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.16.3
    working_directory: ~/circleci-docs
    steps:
      - checkout # special step to check out source code to working directory
      - run:
          name: update-npm
          command: "sudo npm install -g npm@latest"
      - restore_cache: # special step to restore the dependency cache
          # Read about caching dependencies: https://circleci.com/docs/2.0/caching/
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: install-npm
          command: npm install
      - save_cache: # special step to save the dependency cache
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run: # run tests
          name: test
          command: npm test
      # - run: # run coverage report to coveralls
      #     name: code-coverage
      #     command: npm run coverage
      - run: npm run build
      - run: ls -la

    deploy:
      docker:
        - image: circleci/python:3.7-stretch
      working_directory: ~/circleci-docs
      steps:
        - run:
            name: Install awscli
            command: sudo pip install awscli
        - run:
            name: Deploy to S3
            command: aws s3 sync ~/circleci-docs/dist s3://bucketofyanggu/ --delete

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
